language: C

os:
  - linux

cache:
  - apt
  - pip

env:
  global:
    - VER_NGINX=1.9.11
    - COV=1

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
    - lcov
    - cpanminus

install:
  - gem install coveralls-lcov
  - cd ./naxsi_src
  - if [ "$CC" == "clang" ]; then COV=0; fi
  - make
  - cpanm -v --notest Test::Nginx

before_script:
  - lcov --directory "../nginx-${VER_NGINX}" --zerocounters

script: make test

after_success:
 - lcov --directory  "../nginx-${VER_NGINX}/objs/addon/naxsi_src/" --capture --output-file naxsi.lcov --base-directory "../nginx-${VER_NGINX}/"
 - lcov --list naxsi.lcov
 - coveralls-lcov --repo-token ${COVERALLS_TOKEN} naxsi.lcov

